GET http://localhost:3030/hello
###
POST  http://localhost:3030/recettes
###
GET http://localhost:3030/recettes
###
GET http://localhost:3030/recettes/1
###
DELETE http://localhost:3030/recettes/1
###
PUT http://localhost:3030/recettes/1

###

POST http://localhost:3030/recettes
Content-Type: application/json

{
    "nameRecette": "nomfds",
    "lienImageRecette": "lienfdsf",
    "dureeRecette": 1255,
    "noteRecette": 13
}


